# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
    mode: quick
    async: true
    create-group: true
    solc: 0.6.12
    remappings:
        - "@openzeppelin=node_modules/@openzeppelin"
    targets:
        - contracts/iSwap/iSwapPair.sol:iSwapPair
        - contracts/iSwap/iSwapFactory.sol:iSwapFactory
        - contracts/iSwap/iSwapERC20.sol:iSwapERC20
        - contracts/iSwap/iSwapRouter02.sol:iSwapRouter02
        - contracts/XIS.sol:XIS
        - contracts/governance/Timelock.sol:Timelock
